[project]
name = "lambda-mp4-proccessor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.14",
    "requests>=2.32.4",
]
